{
 "title": "AtosOpenSource Demo1",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "CPU sys time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_cpu{cpu=\"cpu0\",mode=\"system\"}[1m])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Available space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_avail{device=\"/dev/sda1\",fstype=\"ext4\",mountpoint=\"/\"} "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "Resident memory" },
    { "expr": "process_virtual_memory_bytes", "legendFormat": "Virtual memory" }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes{device=\"enp0s3\"}[1m])"
    }
   ]
  },
  {
   "title": "Scrapts requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_microseconds{handler=\"prometheus\",quantile=\"0.5\"}[1m])"
    }
   ]
  }
 ]
}