import { OrientedLinkClass } from '../Models/OrientedLinkClass';

export const link: OrientedLinkClass = {
  colorCoordinateA: '#5794F2',
  colorCoordinateB: '#E54658',
  colorMode: false,
  id: 1,
  mainMetric: {
    format: '',
    key: '',
    keyValue: '',
    manageValue: 'avg',
    refId: '',
    returnQuery: [],
    unit: '',
  },
  isIncurved: {
    label: 'No',
    value: false,
  },
  label: '',
  linkURL: {
    followLink: '',
    hoveringTooltipLink: '',
    hoveringTooltipText: '',
  },
  lowerLimit: [],
  meta: '',
  metrics: [],
  name: 'orientedLink1',
  orientationLink: {
    label: 'Monodirectional',
    value: 'AB',
  },
  pointAPositionX: '-14',
  pointAPositionY: '88',
  pointBPositionX: '72',
  pointBPositionY: '70',
  pointCPositionX: '29',
  pointCPositionY: '79',
  pointIn: 'point2',
  pointOut: 'point1',
  positionParameter: {
    labelAPositionX: '0',
    labelAPositionY: '0',
    labelBPositionX: '0',
    labelBPositionY: '0',
    tooltipPositionA: {},
    tooltipPositionB: {},
  },
  regionIn: '',
  regionOut: '',
  textObj: {
    colorBack: '',
    colorText: '',
    generateAuxiliaryElement: {
      addColorBackElement: false,
      addColorTextElement: false,
      colorBackElement: 'black',
      colorTextElement: 'white',
      displayObjectInText: false,
      legendElement: '',
      numericFormatElement: '',
      unit: '',
    },
    generateObjectText: false,
    isTextRegion: false,
    styleText: '',
    value: '',
    valueGenerateObjectText: {
      addColorBackElement: false,
      addColorTextElement: false,
      colorBackElement: 'black',
      colorTextElement: 'white',
      displayObjectInText: false,
      legendElement: '',
      numericFormatElement: '',
      unit: '',
    },
  },
  traceBack: false,
  traceBorder: false,
  valueMainMetricA: '-',
  valueMainMetricB: '-',
  zIndex: '5',
};
